# Determinant
Determinant, kare bir matris ile ilişkili özel bir sayıdır. Bir A matrisin determinant’ı $det(A)$ ya da $|A|$ şeklinde gösterilir ve aşağıdaki şekilde tanımlanır:

$2x2$'lik bir $A$ kare matrisinin determinantı;

$
|A| = \begin{vmatrix}
a_{11} & a_{12}  \\
a_{21} & a_{22} \\
\end{vmatrix}
$=
$a_{1,1}. a_{2,2} - a_{1,2}. a_{2,1}$ 

Determinant, matrisin tersini bulmak, doğrusal denklemleri çözmek, alan ve hacim hesaplamaları gibi birçok alanda kullanılır.

+ Sadece kare matrislerin determinantı vardır.
+ Bir kare matrisin determinantı, o matirisi bir sayıya eşleyen fonksiyondur.
+ Determinant hesabı sonucunda çıkan sayı denklem sistemi çözülebilir mi çözülemez mi, yorum yapmamızı sağlar.
+ Determinant bir matrisin tersinin varlığı hakkında bilgi verir.

# Determinant Hesaplama


## $1x1$ matrislerin determinantı
Kendisine eşittir.

Örneğin, $[a]$ matrisinin determinantı $det([a])=a$ şeklindedir.

## $2x2$ matrislerin determinantı
$2x2$ matrislerin determinantı, aşağıdaki formülle hesaplanır:

$
|A| = \begin{vmatrix}
a & b  \\
c & d  \\
\end{vmatrix}
$
$
= det(A)= a.d-b.c 
$


## $3x3$ matrislerin determinantı
[Sarrus yöntemi](https://tr.wikipedia.org/wiki/Sarrus_kural%C4%B1) ile hesaplanır, bu yöntem Fransız matematikçi Pierre Frédéric Sarrus tarafından keşfedilmiştir. 

$3x3$ bir matrisin determinantını bulmak için önce ilk iki sütundaki elemanlar matrisin altına tekrar yazılır ve aşağıdaki formülle hesaplanır;

$
|A| = \begin{vmatrix}
a & b & c \\
d & e & f \\
g & h & k \\
\end{vmatrix}
$
$\to$
$
\begin{vmatrix}
a & b & c \\
d & e & f \\
g & h & k \\
a & b & c \\
d & e & f \\
\end{vmatrix}
$
$
= det(A)=  (a.e.k + d.h.c + g.b.f) - (c.e.g + f.h.a + k.b.d)
$


## $4x4, 5x5, 6x6, ...$ matrislerin determinantı

## Minör
Matrislerde bir elemanın minörü, o elemanın bulunduğu satır ve sütunun çıkarılması sonucu kalan alt matrisin determinantıdır.

<b>Tanım:</b> Bir kare matrisin $i$'inci satırı ve $j$'inci sütunu silinince geriye kalan kare matrisin determinantına, $a_{i,j}$ elemanının minörü adı verilir. Bu, $M_{i,j}$ ile gösterilir.

### Minör hesaplama
örnek: $a_{21}$ elemanının minörü kaçtır? 

$
A = \begin{bmatrix}
1 & 2 & 3 \\
2 & 1 & 5 \\
-1 & 4 & 2 \\
\end{bmatrix}_{3\times3}
$


Çözüm: 2. satır ve 1. sutun matristen atılır. Geriye kalan alt matrisin determinantı minörü verir.

$
\begin{vmatrix}
2 & 3  \\
4 & 2  \\
\end{vmatrix}
$
$\to$
$2.2-3.4= 4-12= -8$

## Kofaktör 
Kofaktör, bir matrisin herhangi bir elemanının bulunduğu satır ve sütun silinerek elde edilen matrisin işaretli determinantına denir. Bu işlem bütün elemanlar için tekrarlanır ve yerlerine konulursa elde edilen yeni matris kofaktör matris olarak bilinir.

<b>Tanım:</b> Bir matrisin  $a_{i,j}$ elamanına karşılık gelen $(-1)^{i+j}$ ifadesine, bu $a_{i,j}$ elemanının kofaktörü denir ve $K_{i,j}=(-1)^{i+j}$ şeklinde gösterilir.

## Kofaktör hesaplama
<b>örnek:</b> $a_{31}$ elemanının kofaktörü kaçtır? 

$
A = \begin{bmatrix}
1 & 2 & -1 \\
3 & 5 & 2 \\
7 & 1 & 4 \\
\end{bmatrix}_{3\times3}
$


<b>Çözüm:</b> -1 üzeri 3 ile 1 toplanır. 3. satır 1. sütundaki elemanın minörü ile çarpılır (3. satır ve 1. sütun atılır).

$(-1)^{3+1}$
.
$
\begin{vmatrix}
2 & -1  \\
5 & 2  \\
\end{vmatrix}
$
$ \to$ 
$1.(4-(-5))=9$

## Laplace Açılımı ile Determinant Hesabı
$nxm$'lik bir $A$ kare matrisinin determinantı, $i$'inci satıra göre Laplace açılımı ile aşağıdaki gibi hesaplanır:

$$det(A)=|A|= \sum_{j=1}^{n} a_{i,j}.K_{i,j}.M_{i,j}$$

$$i=eleman, K=kofaktor, M=minor $$

Örnek: $detA=?$

$
A = \begin{bmatrix}
1 & 2 & 1 & 0\\
3 & 0 & 2 & -1\\
4 & 1 & 3 & 2\\
0 & 2 & 0 & 0\\
\end{bmatrix}_{4\times4}
$

Çözüm: İşlem kolaylığı için içinde bol sıfır olan satır veya sutun seçilir. 4. satırda bolca sıfır olduğu için onu seçiyoruz. 2 dışındaki matrisin 4. satrırının elemanları sıfır olduğundan dolayı çarpmada gideceklerdir dolayısıyla sadece 2 elemanının minörünü ve kofaktörünü hesaplamak bizi sonuca götürecektir. 

$elemanxkofaktorxminor= 2 x $$(-1)^{4+2}$ x $
\begin{vmatrix}
1 & 1 & 0  \\
3 & 2 & -1  \\
4 & 3 & 2  \\
\end{vmatrix}
$
$=-6$

2. sutun ve 4. satırı matristen attığımız için sarrus yöntemi ile minör hesaplanabilir. Bu hesabın sonucu $-6$ çıkar. Matrisin 4. satırına göre Laplace Açılımı yaparak determinantı hesapladık.

## Determinant özellikleri

1. Matrisin determinantı, matrisin satırlarının veya sütunlarının lineer bağımlılığına bağlıdır. Eğer matrisin bir satırı veya sütunu, diğer satırların veya sütunların doğrusal kombinasyonu olarak ifade edilebilirse, matrisin determinantı sıfırdır.

2. Bir matriste tamamen 0'lardan oluşan satır veya sütun bulunuyorsa o matrisin determinantı 0'dır.

3. Bir matriste bir satır veya sütun, başka bir satır veya sütunun aynısı veya iki katı ise determinant 0 olur.

4. Bir matriste iki satır veya iki sütun yer değiştirirse bunun sonucunda determinantın işareti değişir.

5. Bir satır veya sütunun bir sayı ile çarpılması, matrisin determinantınında o sayı ile çarpılmasını gerektirir.

6. ⭐ Bir satır bir başka satıra eklenir veya çıkartılırsa, bir saır bir sayi ile çarpılıp diğer bir satıra eklenir veya çıkartılırsa determinant değişmez. (Sütun için geçerli değildir.)

7. Köşegen matris, alt üçgen matris ve üst üçgen matrislerde determinant köşegendeki elemanların çarpımına eşittir.

8. Bir matrisin transpozesinin determinantı, orijinal matrisin determinantına eşittir. Yani, $det(A) = det(A^T)$.

9. Bir matrisin tersi varsa, determinantı sıfırdan farklıdır ve matrisin tersi, matrisin kofaktörlerinin transpozesinin, determinantının tersi ile çarpımına eşittir.

10. $det(A.B)= detA.detB$

11. $det(A^n)=(detA)^n$

12. $det(k.A)=k^{satirsayisi}.detA=k^n.detA$

<hr>

## Elemanter Satır İşlemleri

### Satırı Skaler ile Çarpma

Bir matrisin herhangi bir satırındaki tüm elemanları belirli bir sayıyla çarpmak, o satırı bu sayıya göre ölçeklendirir. Örneğin, aşağıdaki matrisin ilk satırını 2 ile çarparsak:

$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
\to
\begin{bmatrix}
2 & 4 & 6 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
$

### Satırın Bir Katını Başka Bir Satıra Ekleme

Bir matrisin bir satırının bir katını başka bir satıra eklemek, matrisin bu iki satırının toplamına eşit olan yeni bir matris oluşturur. Örneğin, aşağıdaki matrisin ilk satırının 2 katını 2. satıra eklersek:

$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
\to
\begin{bmatrix}
1 & 2 & 3 \\
6 & 9 & 12 \\
7 & 8 & 9 \\
\end{bmatrix}
$

### İki Satırın Yerlerini Birbiri ile Değiştirme

İki satırın yerlerini birbiri ile değiştirmek, matrisin iki satırını yer değiştirerek yeni bir matris oluşturur. Örneğin, aşağıdaki matrisin 1. ve 2. satırlarını birbiri ile değiştirirsek:

$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
\to
\begin{bmatrix}
4 & 5 & 6 \\
1 & 2 & 3 \\
7 & 8 & 9 \\
\end{bmatrix}
$


<hr style="border: 0.5px solid gray; margin: 25px 0;">

## Matrislerde Satır Eşdeğerliği
<b>Tanım:</b> Bir $A$ matrisinin üzerinde elemanter satır işlemlerinden bir veya daha fazlasının uygulanması sonucunda elde edilen matris $B$ ile gösterilsin. $B$ matrisi $A$ matrisinin <b>"satır eşdeğeridir"</b> denir ve $A \sim B$ ile gösterilir.

Örnek: 
$$
A = \begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix} 
\to
B = \begin{bmatrix} 
4 & 5 & 6 \\
1 & 2 & 3 \\ 
7 & 8 & 9 \\
\end{bmatrix} 
$$

Matris $A$'nın 1. satırı ile 2. satırları yer değiştirdiğinde ortaya çıkan $B$ matrisi, $A$ matrisi ile satır eşdeğeridir.

<hr style="border: 0.5px solid gray; margin: 25px 0;">

## Matrislerin Tersi
<b>Tanım:</b> "Bir kare matrisi aynı mertebeden hangi kare matrisle çarparsak birim matrisi elde ederiz?" sorusunun cevabı varsa, bu matrise <b>ters matris</b> denir. Bir $A$ kare matrisinin eğer tersi varsa bu ters matris $A^{-1}$ ile gösterilir ve $AA^{-1}=I$'dır. $I$, $A$ matrisleriyle aynı mertebeden birim matristir.

Bir kare matrisin tersini bulmak için pek çok yol mevcuttur. Bunlardan biri elemanter satır işlemleri ile ters bulmaktır.

<b>Teorem:</b> $[A|I]$, $A$ matrisinin sağına aynı mertebeden birim matrisin eklenmiş halini göstersin. $[A|I]$ genişletilmiş matrisine elemanter satır işlemleri uygulanarak elde edilecek $[I|B]$ formundaki satır eşdeğer matriste yer alan $B = A^{-1}$'dir.

#### Not: $[A|I] \sim  [I|B] \to B = A^{-1}$

Örnek: Aşağıdaki $A$ matrisinin tersini elemanter satır işlemlerine dayalı olarak elde edelim.

$
A = \begin{bmatrix}
2 & 3 \\
1 & 5 \\
\end{bmatrix}
$

Çözüm: $[A|I] = 
\begin{vmatrix}
2 & 3 |1 & 0 \\
1 & 5 |0 & 1  \\
\end{vmatrix}
$

Oluşturulsun. Bu matrisin sol tarafına birim matris oluşturulacak şekilde elemanter satır işlemleri uygulayalım: Önce 2 elemanını 1, sonra 1 elemanını 0, daha sonra 5 elemanını 1 ve en son olarak 3 elemanını 0 haline getirecek elemanter satır işlemlerini uygulamalıyız.

$
\begin{vmatrix}
2 & 3 |1 & 0 \\
1 & 5 |0 & 1  \\
\end{vmatrix}
$
$\to$
$
\begin{vmatrix}
1 & 3/2 |1/2 & 0 \\
1 & 5   |0 & 1  \\
\end{vmatrix}
$
$\to$
$
\begin{vmatrix}
1 & 3/2 |1/2 & 0 \\
0 & 7/2 |1/2 & 1  \\
\end{vmatrix}
$
$\to$
$
\begin{vmatrix}
1 & 3/2 |1/2 & 0 \\
0 & 1   |-1/7 & 2/7  \\
\end{vmatrix}
$
$\to$
$
\begin{vmatrix}
1 & 0 | 5/7 & -3/7 \\
0 & 1 | -1/7 & 2/7  \\
\end{vmatrix}
$
$\to$
$[I|A^{-1}]$

Sonuç olarak,

$A^{-1} = \begin{bmatrix}
\frac{5}{7} & -\frac{3}{7} \\
-\frac{1}{7} & \frac{2}{7} \\
\end{bmatrix}$ 
elde edilir.

### Önemli Not: Solda birim matris elde edilirken; önce 1 oluşutulur, sonra 1 elemanının bulunduğu sütunlar diğer elemanlar sırayla sıfırlancak şekilde elemanter satır işlemleri yapılır. Bu kural sutunlarda sırayla uygulanır. Örneğin,

$[A|I] = 
\begin{vmatrix}
a & d & g|1 & 0 & 0\\
b & e & h|0 & 1 & 0\\
c & f & i|0 & 0 & 1\\
\end{vmatrix}
$

1. Adım: $a$ elemanını $1$ yapacak elemanter satır işlemini yap.
2. Adım: $b$ elemanını $0$ yapacak elemanter satır işlemini yap.
3. Adım: $c$ elemanını $0$ yapacak elemanter satır işlemini yap.
4. Adım: $e$ elemanını $1$ yapacak elemanter satır işlemini yap.
5. Adım: $d$ elemanını $0$ yapacak elemanter satır işlemini yap.
6. Adım: $f$ elemanını $0$ yapacak elemanter satır işlemini yap.
7. Adım: $i$ elemanını $1$ yapacak elemanter satır işlemini yap.
8. Adım: $g$ elemanını $0$ yapacak elemanter satır işlemini yap.
9. Adım: $h$ elemanını $0$ yapacak elemanter satır işlemini yap.

## Bir Matrisin Tersinin Olma Şartları

+ Matris kare bir matris olmalıdır. Yani, $A m x n$ boyutunda bir matris ise, $m = n$ olmalıdır.
+ Matrisin determinantının sıfır olmaması gerekir $det(A) ≠ 0$ Eğer bir matrisin determinantı sıfır ise, o matris tekil (singular) olarak adlandırılır ve tersi yoktur veya tanımsızdır.

## Ters Matris Özellikleri

+ Bir matrisin tersi yalnızca tek bir tane olabilir veya hiç olmayabilir.
+ Ters matris, birim matris ile çarpıldığında her zaman birim matrisi verir: $A x A^{-1} = A^{-1} x A = I$.
+ Bir matrisin tersi varsa, o matrisin determinantı sıfırdan farklıdır. Bu nedenle, bir matrisin determinantı sıfır ise, tersi yoktur.
+ Bir matrisin tersinin tersi kendisidir.
+ Birim matrisin tersi kendisidir.
+ Bir matrisin tersinin transpozu, transpozunun tersine eşittir.
+ Bir matrisin tersi varsa, sıfırdan farklı bir reel sayı ile çarpımının tersi, tersinin reel sayının çarpmaya göre tersi ile çarpımına eşittir.
+ İki ya da daha fazla matrisin tersi varsa, çarpımlarının da tersi vardır ve matrislerin terslerinin ters sırada çarpımına eşittir.

<hr style="border: 0.5px solid gray; margin: 25px 0;">

## Python Uygulamaları

### Determinant
Python'da determinant hesaplamak için `linalg.det` metodu kullanılabilir. Bu metod determinantı hesaplamak için arka planda <b>LU</b> ayrıştırması yöntemini kullanır. LU ayrıştırması yapıldıktan sonra matrisin determinantı üst üçgensel matrisin çapraz elemanlarının çarpımına eşit gelir.

In [1]:
import numpy as np

matris1 = np.array([[5]]) # 1x1 boyutunda matris

matris2 = np.array([[4, 3], # 2x2 boyutunda matris
                    [6, 5]]) 

matris3 = np.array([[6, 5, 1],  # 3x3 boyutunda matris
                    [4, 3, 2], 
                    [3, 2, 1]])

matris4 = np.array([[1, 2, 3, 4], # 4x4 boyutunda matris
                    [0, 1, 2, 3], 
                    [0, 0, 1, 2], 
                    [0, 0, 0, 1]]) 

matrisler = [matris1, matris2, matris3, matris4]

for matris in matrisler:
    boyut = matris.shape[0]
    determinant = np.linalg.det(matris)
    print(f'{boyut}x{boyut} matrisin determinantı: {determinant}')

1x1 matrisin determinantı: 4.999999999999999
2x2 matrisin determinantı: 1.999999999999998
3x3 matrisin determinantı: 3.000000000000001
4x4 matrisin determinantı: 1.0


### Minör
Python'da minör hesabı için yerleşik bir metod yoktur. Minörü hesaplayabimek için `delete` metodu ile ilgili satır ve sütun matristen atılır geriye kalan matrisin determinantı bize minörü verecektir.

In [2]:
import numpy as np

matris = np.array([[1, 2, 3], 
                   [2, 1, 5], 
                   [-1, 4, 2]])

# 2. satır 1. sütuna göre minörü hesaplayalım
# 2. satır ve 1. sütun matristen atılır
minor_matris = np.delete(np.delete(matris, 1, axis=0), 0, axis=1)

# geriye kalan matrisin determinantı minöre eşittir
minor = np.linalg.det(minor_matris)

print(minor_matris, '\n','Minör= ', minor)

[[2 3]
 [4 2]] 
 Minör=  -7.999999999999998


### Kofaktör
Python'da bir kofaktör matrisi oluşturmak için yerleşik bir metod yoktur. Kofaktör hesabı oluşturmak için bir fonksiyon tanımladık. Bu fonksiyon ilk olarak matrisin boyutunu alır, sadece kare matrislerin kofaktörü olduğu için ilk indisi almak yeterlidir. Akabinde matrisin boyutunun 1x1 olup olmadığı kontol eder devamında boş bir matris oluşturur. For döngüleri ile matrisin her bir elemanının kofaktörü hesaplanır. Dıştaki for döngüsü matrisin satırlarını, içteki for döngüsü ise sütunlarını tarar ve kofaktör hesabını yapar. En sonunda kofaktör matrisini döndürür.

In [3]:
import numpy as np
matris = np.array([[1, 2, -1], 
                   [3, 5, 2], 
                   [7, 1, 4]])

def kofaktor(matris):
    boyut = matris.shape[0] # Matrisin boyutunu al
    
    # Eğer matris 1x1 boyutundaysa, kofaktörü 1 olarak dön
    if boyut == 1:
        return np.array([[1]])

    # Kofaktör matrisi için boş bir matris oluştur
    kofaktor_matrisi = np.zeros((boyut, boyut))

    # Her bir elemanın kofaktörünü hesapla
    for i in range(boyut):
        for j in range(boyut):
            # Matrisin i. satırını ve j. sütununu silerek minör matrisi oluştur
            minordeki_determinant = np.linalg.det(np.delete(np.delete(matris, i, axis=0), j, axis=1))
            # İşaretlendirme kuralı uygula
            isaret = (-1) ** (i + j)
            # Kofaktör matrisindeki i,j elemanını hesapla
            kofaktor_matrisi[i, j] = isaret * minordeki_determinant

    return kofaktor_matrisi

print(kofaktor(matris))

[[ 18.   2. -32.]
 [ -9.  11.  13.]
 [  9.  -5.  -1.]]


### Laplace Açılımı ile Determinant Hesabı 
Laplace açılımı ile determinanat hesaplamak için özyineli bir fonksiyon tanımladık. Bu durumda determinant fonksiyonu kendisini matrisin alt matrislerine uygulayarak çağırır. Fonksiyon parametre olarak hesaplanacak matrisi alır. Öncelikle matrisin boyutunu belirler ve matris boyutu 1 ise matrisin tek elemanını determinant olarak döndürür. Daha sonra, matris boyutu 2 veya daha büyükse, Laplace Açılımı yöntemini kullanarak matrisin determinantını hesaplar.

In [4]:
import numpy as np

matris = np.array([[1, 2, 1, 0], 
                   [3, 0, 2, -1], 
                   [4, 1, 3, 2],
                   [0, 2, 0, 0]])

def laplace_det(matris):
    boyut = len(matris) # matrisin boyutu
    
    if boyut == 1: # boyut 1 ise determinant kensisine eşittir
        return matris[0][0]
    
    # Matris 2x2 ise formülü uygula
    elif boyut == 2:
        return matris[0][0]*matris[1][1] - matris[0][1]*matris[1][0]
    
    # Boyut 2'den büyükse Laplace açılımı kullanılabilir
    else:
        det = 0
        for j in range(boyut):
            isaret = (-1) ** j # işaret kuralı
            
            # Alt matrisi hesapla
            alt_matris = np.delete(matris, 0, axis=0)
            alt_matris = np.delete(alt_matris, j, axis=1)
            
            # Alt matrisin determinantı
            alt_det = laplace_det(alt_matris)
            
            # Kofaktörü hesapla ve topla
            det += isaret * matris[0][j] * alt_det
            
        return det

print(laplace_det(matris))

-6


### Elemanter Satır İşlemleri

In [5]:
import numpy as np
matris = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# İlk satırı 2 ile çarpıyoruz
matris[0] = matris[0] * 2
print(matris)

[[2 4 6]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np
matris = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# İlk satırın 2 katını 2. satıra ekliyoruz
matris[1] = matris[1] + matris[0] * 2
print(matris)

[[ 1  2  3]
 [ 6  9 12]
 [ 7  8  9]]


In [7]:
import numpy as np
matris = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 1. ve 2. satırları birbiri ile değiştiriyoruz
matris[[0, 1]] = matris[[1, 0]]
print(matris)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


### Matrislerde Satır Eşdeğerliği
Matrislerin satır eşdeğerliğini kontrol etmek için, matrislerin ranklarını `linalg.matrix_rank` metodu ile hesaplayalım ve karşılaştıralım. Eğer ranklar eşlit çıkarsa matrisler satır eşdeğeridir.

In [8]:
import numpy as np

A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[4, 5, 6], 
              [1, 2, 3], 
              [7, 8, 9]])

# Matrislerin ranklarını hesaplıyoruz
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

print(rank_A, rank_B)

# Ranklar eşitse matrisler satır eşdeğeridir
if rank_A == rank_B:
    print("Matrisler satır eşdeğeridir.")
else:
    print("Matrisler satır eşdeğer eşdeğeridir.")

2 2
Matrisler satır eşdeğeridir.


### Matrislerin Tersi
Python'da bir matrisin tersini almak için `linalg.inv()` metodu kullanılabilir. Eğer bir matrisin determinantı sıfırsa o matrisin tersi yoktur. Bu nedenden dolayı tersi alınacak matrisin determinantı kontrol edilmelidir.

In [9]:
import numpy as np

A = np.array([[2, 3], 
              [1, 5]])

if np.linalg.det(A) == 0:
    print('Matrisin tersi yoktur.')
else:
    Ters_matris = np.linalg.inv(A)
    print(Ters_matris)                                                                                

[[ 0.71428571 -0.42857143]
 [-0.14285714  0.28571429]]


## Alıştırmalar:

#### 1. Python'da verilen bir matrisin determinantını, minörünü ve kofaktörünü hesaplayan bir fonksiyon yazınız.
#### 2. Elemanter satır işlemleri nelerdir ve ne işe yararlar?
#### 3. Laplace Açılımı hangi durumlarda kullanılır ve kullanım avantajları nelerdir?
#### 4. Elemanter satır işlemleri ile hangi matris işlemleri yapılabilir?
#### 5. Her matrisin tersi bulunabilir mi ve bununla ilgili hangi teoremler ve kanıtlar vardır?