## Örnek Sorular
El ile kendiniz çözünüz, burada Python ile çözümleri verilmiştir.

**Soru1:** Aşağıda verilen matrisin rankını bulalım.

$
A = \begin{bmatrix}
2 & 8 & 6 \\
1 & 4 & -1 \\
0 & 2 & 1
\end{bmatrix}
$

### Python İle Çözüm

In [1]:
import numpy as np

A = np.array([[2, 8, 6],
              [1, 4, -1],
              [0, 2, 1]])

rank = np.linalg.matrix_rank(A)

print("Matrisin rankı:", rank)

Matrisin rankı: 3


<hr style="border: 0.5px solid gray; margin: 25px 0;">

**Soru2:** Cayley Hamilton Teoremine dayalı olarak $B^{-1}$'i bulalım.

$
B = \begin{bmatrix}
2 & 1 & 3 \\
3 & 1 & 0 \\
0 & 2 & 4
\end{bmatrix}
$

### Python İle Çözüm

In [2]:
import numpy as np

B = np.array([[2, 1, 3], 
              [3, 1, 0], 
              [0, 2, 4]])

# karakteristik polinom
P = np.poly(B)

# matrisin tersi
ters_matris = np.linalg.inv(B)

print(ters_matris)

[[ 0.28571429  0.14285714 -0.21428571]
 [-0.85714286  0.57142857  0.64285714]
 [ 0.42857143 -0.28571429 -0.07142857]]
