## Matrislerin Boyutları ve Eleman Kümesi Belirleme

<b>Tanım:</b> $nxm$ mertebesinden yazılabilecek matrisler kümesi $M_{n,m}(F)$ ile gösterilir. Burada $F$, matrisin elemanlarının hangi kümeye ait olğunu gösterir. Ayrıca, $M_{n}(F)$, $nxm$'lik kare matrisler kümesini ifade eder.  

## Matrislerin Eşitliği

Matrislerin eşitliği, iki veya daha fazla matrisin aynı boyutta olması ve her bir öğelerinin karşılıklı olarak eşit olması durumudur.

<b>Tanım:</b> $A$ ve $B$ matrislerinin <b>"Eşit Matrisler"</b> olması demek $a_{i,j} = b_{i,j}$ ($\forall i,j$ için) ve metebelerinin aynı olması demektir. Bu durum $A=B$ ile gerçekleşir.             

Örnek:

$
A = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}, \quad
B = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

$
X = \begin{bmatrix}
3 & 3 & 3 \\
3 & 3 & 3 \\
\end{bmatrix}, \quad
Y = \begin{bmatrix}
3 & 3 & 3 \\
3 & 3 & 3 \\
\end{bmatrix}
$


## Matrislerde İşlemler

Sayı kümeleri üzerinde yaptığımız toplama, çıkarma, çarpma ve bölme işlemleri matrisler üzerinde çok kısıtlı olarak yapılabiliyor.

### Matrislerde Toplama İşlemi

Boyutlar aynı olmalı. Aynı satır ve sütundaki elemanlar toplanır. Matrislerde toplama işleminin değişme ve birleşme özellikleri vardır.

<b>Tanım:</b> $A \in M_{n,m}(F)$ ve $B \in M_{n,m}(F)$ olmak üzere bu iki matrisin toplamı $C$ ile gösterilsin. Bu durumdas $C = A+B$ işlemi; $i \in \left\{ 1,2,3,\ldots,n \right\}$ ve $j \in \left\{ 1,2,3,\ldots,m \right\}$ için $c_{i,j}=a_{i,j}+b_{i,j}$ şeklinde tanımlanır. ($a_{i,j} \in F$; $b_{i,j} \in F$, $c_{i,j} \in F$ )

### Özellikler:
+ Değişme özelliği: $A + B = B + A$
+ Birleşme özelliği: $A + (B + C) = (A + B) + C$
+ Kapalılık özelliği: $A$ ve $B$ matrisleri aynı boyutta ise, $A + B$ de aynı boyutta bir matristir.
+ Etkisiz eleman: Sıfır matrisi O, herhangi bir matrisin A toplamına etki etmez. Yani, $A + O = O + A = A$

Örnek:

$
A = \begin{bmatrix}
2 & 3 & 4  \\
5 & -1 & 6 \\
\end{bmatrix}
$
<b>,</b>
$
B = \begin{bmatrix}
1 & 0 & 0  \\
2 & -6 & -3 \\
\end{bmatrix}
$
<b>ise</b>


$C=A+B=$
$
\begin{bmatrix}
2+1 & 3+0 & 4+0  \\
5+2 & -1+(-6) & 6+(-3) \\
\end{bmatrix}
$
=
$
\begin{bmatrix}
3 & 3 & 4  \\
7 & -7 & 3 \\
\end{bmatrix}
$

### Matrislerde Çıkarma İşlemi

Boyutlar aynı olmalı. Aynı satır ve sütundaki elemanlar toplanır. Matrislerde çıkarma işleminin değişme özelliği yoktur.

<b>Tanım:</b> $A \in M_{n,m}(F)$ ve $B \in M_{n,m}(F)$ olmak üzere bu iki matrisin farkı $C$ ile gösterilsin. Bu durumdas $C = A-B$ işlemi; $i \in \left\{ 1,2,3,\ldots,n \right\}$ ve $j \in \left\{ 1,2,3,\ldots,m \right\}$ için $c_{i,j}=a_{i,j}-b_{i,j}$ şeklinde tanımlanır. ($a_{i,j} \in F$; $b_{i,j} \in F$, $c_{i,j} \in F$ )

### Özellikler:
+ Kapalılık özelliği: $A$ ve $B$ matrisleri aynı boyutta ise, $A - B$ de aynı boyutta bir matristir.
+ Değişme özelliği yoktur: $A - B ≠ B - A$
+ Birleşme özelliği: $A - (B + C) = (A - B) - C$
+ Etkisiz eleman: Sıfır matrisi $O$, herhangi bir matrisin $A$ farkına etki etmez. Yani, $A - O = O - A = A$

Örnek:

$
A = \begin{bmatrix}
2 & 3 & 4  \\
5 & -1 & 6 \\
\end{bmatrix}
$
<b>,</b>
$
B = \begin{bmatrix}
1 & 0 & 0  \\
2 & -6 & -3 \\
\end{bmatrix}
$
<b>ise</b>


$C=A-B=$
$
\begin{bmatrix}
2-1 & 3-0 & 4-0  \\
5-2 & -1-(-6) & 6-(-3) \\
\end{bmatrix}
$
=
$
\begin{bmatrix}
1 & 3 & 4  \\
3 & 5 & 9 \\
\end{bmatrix}
$

### Skaler Çarpma İşlemi

Bir matrisin tüm elemanlarının belirli bir sayı ile çarpılmasıdır. Bu işlem sonucunda, her bir matris elemanı, verilen sayı ile çarpılmış halini alır.

<b>Tanım:</b> $A \in M_{n,m}(F)$ ve $c \in F$ ise $A$ matrisinin $c$ skaleri ile çarpımına <b>"Skaler Çarpım"</b> adı verilir ve bu çarpım $B$ ile gösterilirse ($B=cA=Ac$); $i \in \left\{ 1,2,3,\ldots,n \right\}$ ve $j \in \left\{ 1,2,3,\ldots,m \right\}$ için $b_{i,j}:=c.a_{i,j}$ şeklinde tanımlanır. Burada $B \in M_{n,m}(F)$.

### Özellikler:
+ Değişme özelliği: $c x A = A x c$
+ Dağılma özelliği: $c x (A + B) = c x A + c x B$
+ Birim eleman: $1 x A = A$
+ Sıfır eleman: $0 x A = O$

Örnek:

$
A = \begin{bmatrix}
12 & 6 \\
3 & 1 \\
\end{bmatrix}
$
$=>$
$1/3xA=$
$
 \begin{bmatrix}
12/3 & 6/3 \\
3/3 & 1/3 \\
\end{bmatrix}
$
=
$
\begin{bmatrix}
4 & 2 \\
1 & 1/3 \\
\end{bmatrix}
$

### Noktasal Skaler Çarpım

Matrislerde noktasal skaler çarpım, bir matrisin her bir ögesinin aynı sayı (skaler) ile çarpılmasıdır.

<b>Tanım:</b> $A ve B \in M_{1,m}(\text {IR})$ olsun $A$ ve $B$ matrislerinin (vektörlerinin) noktasal (skaler) çarpımı $<A,B>$ ile gösterilir be bu sonuç $D$ ile gösterilirse ($D:=<A,B>$)

$D=<A,B>= \sum\limits_{i=1}^m a_{1,i} b_{1,i} \in \text {IR}$ şeklinde tanımlanır.

Örnek:

$
A = \begin{bmatrix}
2 & 8 & -1  \\
\end{bmatrix}
$
,
$
B = \begin{bmatrix}
1 & 2 & 0  \\
\end{bmatrix}
$ 
ise
= 
$(2x1)+(8x2)+(-1x0)= 2+16+0=18$

### Noktasal skaler çarpım ile skaler çarpım arasındaki fark:
+ Noktasal skaler çarpım, iki vektörün birbirine dik olan bileşenlerinin çarpılması ve toplanmasıyla elde edilen bir işlemdir. Sonucu bir skalerdir (bir sayı).
+ Skaler çarpım ise, bir vektörün her bir ögesinin aynı sayı (skaler) ile çarpılmasıyla elde edilen bir işlemdir. Sonucu yine bir vektördür.

### Matrislerde Çarpma İşlemi


İki matrisin çarpılabilmesi için, sol taraftaki matrisin sütun sayısı sağ taraftaki matrisin satır sayısına eşit olmalıdır. Yani, eğer $A$ matrisi $m \times n$ boyutunda ve $B$ matrisi $n \times p$ boyutunda ise, $A$ ve $B$ matrisleri çarpılabilir ve sonuç olarak $C$ matrisi elde edilir. Bu durumda, $C$ matrisi $m \times p$ boyutunda olur.

Matris çarpımı, aşağıdaki gibi hesaplanır:

$$C_{i,j} = \sum_{k=1}^{n} A_{i,k}B_{k,j}$$

Burada $C_{i,j}$, $C$ matrisinin $i$'inci satır ve $j$'inci sütunundaki elemanı ifade eder. $A_{i,k}$, $A$ matrisinin $i$'inci satır ve $k$'inci sütunundaki elemanıdır. $B_{k,j}$, $B$ matrisinin $k$'inci satır ve $j$'inci sütunundaki elemanıdır.


### Özellikleri:
+ Çarpma işlemi, matrisler arasında dağılma özelliği gösterir. Yani, $(A+B)C = AC+BC$ ve $A(B+C) = AB+AC$ şeklinde dağılma özelliği vardır.

+ Çarpma işlemi, matrisler arasında birleşme özelliği gösterir. Yani, $A(BC) = (AB)C$ şeklinde birleşme özelliği vardır.

+ Çarpma işlemi, matrisler arasında işlem yapılan matrislerin sırasını değiştirme özelliğine sahiptir. Yani, $AB \neq BA$ genellikle geçerlidir.

+ Çarpma işlemi, bir matris ile bir skaler (sabit sayı) arasında işlem yapılabilir. Bu durumda, her elemanı skalerle çarpılır. Örneğin, $kA$ matrisi, $A$ matrisinin her elemanını $k$ ile çarpılarak elde edilir.

+ Bir matris, kendisi ile çarpıldığında kare matris haline gelir. Yani, $AA=A^2$ şeklinde ifade edilebilir.

+ Bir matris, 0 matrisi ile çarpıldığında 0 matrisi elde edilir. Yani, $A\mathbf{0} = \mathbf{0}$ şeklinde ifade edilebilir.

Örnek:


$
A = \begin{bmatrix}
\color{red}2 & \color{red}3 & \color{red}4 \\
\color{blue}5 & \color{blue}-1 & \color{blue}-6 \\
\end{bmatrix}_{\color{red}2\times 3},\quad
B = \begin{bmatrix}
\color{green}1 & \color{orange}2 \\
\color{green}-3 & \color{orange}4 \\
\color{green}4 & \color{orange}-2 \\
\end{bmatrix}_{\color{green}3\times 2}
$

Bu matrislerin çarpımı:

$
C = AB = \begin{bmatrix}
2\cdot1 + 3\cdot(-3) + 4\cdot4 & 2\cdot2 + 3\cdot4 + 4\cdot(-2) \\
5\cdot1 + (-1)\cdot(-3) + (-6)\cdot4 & 5\cdot2 + (-1)\cdot4 + (-6)\cdot(-2) \\
\end{bmatrix}
= \begin{bmatrix}
9 & 8 \\
-16 & 18 \\
\end{bmatrix}_{2\times 2}
$

+ İlk matrisin sütun sayısı, ikinci matrisin satır sayısına eşit olmalıdır.
+ Matris çarpımında boyutların aynı olması gibi bir kural yoktur.

## Python Uygulamaları

### Bir Matrisin Boyutunu Görme
NumPy'da matrislerin boyutunu görmek için `shape` metodu kullanılır.

In [1]:
import numpy as np
matris = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])
boyut = matris.shape
print(boyut)

(3, 4)


### Bir Matrisin Benzersiz Elemanlarını Bulma
Tanımlanmış matrisi `flatten()` metodu ile tek boyuta indirgeriz akabinde Python'da yerleşik bulunan `set` veri yapısı ile benzersiz değerleri buluruz.

In [2]:
import numpy as np
matris = np.array([[1, 2, 3], 
                   [2, 3, 4], 
                   [3, 4, 5]])
# boyut indirgeme
birlesik_dizi = matris.flatten()

# küme(set) veri yapısına çevirme
eleman_kumesi = set(birlesik_dizi)

print(eleman_kumesi)

{1, 2, 3, 4, 5}


### Matrislerin Eşitliği
Matrislerin eşitliğini `array_equal()` metodu ile kontrol edebileceğimiz gibi `==` operatörü ile de kontrol edebiliriz.

In [3]:
import numpy as np

matris1 = np.array([[1, 2], [3, 4]])
matris2 = np.array([[1, 2], [3, 4]])

if np.array_equal(matris1, matris2):
    print("Matrisler eşittir.")
else:
    print("Matrisler eşit değildir.")
# 2. yol
print(matris1 == matris2)

Matrisler eşittir.
[[ True  True]
 [ True  True]]


### Matrislerde Toplama İşemi
Boyutları aynı tanımlanmış matrisler `+` operatörü ile kolayca toplanabilir. Ancak toplanacak matrislerin boyutları aynı olmadığında hata verecektir.

In [4]:
import numpy as np

matris1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])

matris2 = np.array([[7, 8, 9], 
                    [10, 11, 12]])

# boyut kontrolü
if matris1.shape == matris2.shape:
    toplam_matrisi = matris1 + matris2
    print(toplam_matrisi)
else:
    print('Boyutlar aynı olmadığı için toplama işlemi yapılamaz.')

[[ 8 10 12]
 [14 16 18]]


### Matrislerde Çıkarma İşemi
Boyutları aynı tanımlanmış matrisler `-` operatörü ile kolayca fark işlemi yapılabilir. Ancak fark işlemi yapılacak matrislerin boyutları aynı olmadığında hata verecektir.

In [5]:
import numpy as np

matris1 = np.array([[-1, 2, 5], 
                    [12, 9, 6]])

matris2 = np.array([[8, 8, 4], 
                    [19, 21, 11]])

if matris1.shape == matris2.shape:
    cikarma_matrisi = matris1 - matris2
    print(cikarma_matrisi)
else:
    print('Boyutlar aynı olmadığı için çıkarma işlemi yapılamaz.')

[[ -9  -6   1]
 [ -7 -12  -5]]


### Matrislerde Skaler Çarpma İşlemi
Bir skaler `*` operatörü ile matrisin her elemanıyla çarpılabilir.

In [6]:
import numpy as np

matris = np.array([[1, 2, 3], 
                   [4, 5, 6]])
skaler = 3

carpim_matrisi = skaler * matris

print(carpim_matrisi)

[[ 3  6  9]
 [12 15 18]]


### Matrislerde Çarpma İşlemi
Çarpma işlemini gerçekleştirmek için `dot()` metodu kullanılabileceği gibi `@` operatörü de kullanılabilir.

In [7]:
import numpy as np

matris1 = np.array([[1, 2], 
                    [3, 4]])

matris2 = np.array([[5, 6], 
                    [7, 8]])

matris_carpimi1 = np.dot(matris1, matris2)
matris_carpimi2 = matris1 @ matris2

print(matris_carpimi1, '\n-----------------', '\n', matris_carpimi2)

[[19 22]
 [43 50]] 
----------------- 
 [[19 22]
 [43 50]]


## Alıştırmalar:

#### 1. Bir matrisi 0 skaleri ile çarparsak ne olur?
#### 2. Bir matrisi 1 skaleri ile çarparsak ne olur?
#### 3. `[[1,2],[0,1],[1,-1]]x[[2,1,0],[3,-1,1]]` işlemini el ile yapın
#### 4. Matrisler hangi durumlarda eşit sayılır?
#### 5. Matrislerde çarpma çeşitleri nelerdir, Python'da örnekleyiniz.