# Toplama İşlemi

In [1]:
import numpy as np

def matris_topla(matris1, matris2):
    if matris1.shape == matris2.shape:
        toplam_matrisi = matris1 + matris2
        return toplam_matrisi
    else:
        print('Boyutlar aynı olmadığı için toplama işlemi yapılamaz.')
        

matris1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])

matris2 = np.array([[7, 8, 9], 
                    [10, 11, 12]])

print(matris_topla(matris1, matris2))

[[ 8 10 12]
 [14 16 18]]


# Çıkarma İşlemi

In [2]:
import numpy as np

def matris_cikar(matris1, matris2):
    if matris1.shape == matris2.shape:
        cikarma_matrisi = matris1 - matris2
        return cikarma_matrisi
    else:
        print('Boyutlar aynı olmadığı için çıkarma işlemi yapılamaz.')

matris1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])

matris2 = np.array([[7, 8, 9], 
                    [10, 11, 12]])

print(matris_cikar(matris1, matris2))

[[-6 -6 -6]
 [-6 -6 -6]]


# Skaler İle Çarpma

In [3]:
import numpy as np

def matris_carp_skaler(matris, skaler):
    carpim_matrisi = skaler * matris
    return carpim_matrisi

matris = np.array([[1, 2, 3], 
                    [4, 5, 6]])

skaler = 3


print(matris_carp_skaler(matris, skaler))

[[ 3  6  9]
 [12 15 18]]


# Çarpma İşlemi

In [4]:
import numpy as np

def matris_carp(matris1, matris2):
    matris_carpimi = np.dot(matris1, matris2)
    return matris_carpimi


matris1 = np.array([[1, 2], 
                    [3, 4]])

matris2 = np.array([[5, 6], 
                    [7, 8]])

print(matris_carp(matris1, matris2))

[[19 22]
 [43 50]]


# Determinant Hesabı

In [5]:
import numpy as np

def determinant(matris):
    det = np.linalg.det(matris)
    return det

matris = np.array([[1, 2], 
                   [3, 4]])

print(determinant(matris))

-2.0000000000000004


# Minör Hesabı

In [6]:
import numpy as np

def matris_minor(matris, row, col):
    # belirtilen satır ve sütun matristen atılır
    minor_matris = np.delete(np.delete(matris, row-1, axis=0), col-1, axis=1)
    # geriye kalan matrisin determinantı minöre eşittir
    minor = np.linalg.det(minor_matris)
    return minor


matris = np.array([[1, 2, 3], 
                   [2, 1, 5], 
                   [-1, 4, 2]])

print(matris_minor(matris, 2, 1))

-7.999999999999998


# Kofaktör Hesabı

In [7]:
import numpy as np

def kofaktor(matris):
    boyut = matris.shape[0] # Matrisin boyutunu al
    
    # Eğer matris 1x1 boyutundaysa, kofaktörü 1 olarak dön
    if boyut == 1:
        return np.array([[1]])

    # Kofaktör matrisi için boş bir matris oluştur
    kofaktor_matrisi = np.zeros((boyut, boyut))

    # Her bir elemanın kofaktörünü hesapla
    for i in range(boyut):
        for j in range(boyut):
            # Matrisin i. satırını ve j. sütununu silerek minör matrisi oluştur
            minordeki_determinant = np.linalg.det(np.delete(np.delete(matris, i, axis=0), j, axis=1))
            # İşaretlendirme kuralı uygula
            isaret = (-1) ** (i + j)
            # Kofaktör matrisindeki i,j elemanını hesapla
            kofaktor_matrisi[i, j] = isaret * minordeki_determinant

    return kofaktor_matrisi

matris = np.array([[1, 2, -1], 
                   [3, 5, 2], 
                   [7, 1, 4]])


print(kofaktor(matris))

[[ 18.   2. -32.]
 [ -9.  11.  13.]
 [  9.  -5.  -1.]]


# Satır Eşdeğerliği

In [8]:
import numpy as np

def satir_esdeger_mi(matris1, matris2):
    rank_matris1 = np.linalg.matrix_rank(matris1)
    rank_matris2 = np.linalg.matrix_rank(matris2)
    if rank_matris1 == rank_matris2:
        return True
    else:
        return False
    
matris1 = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])

matris2 = np.array([[4, 5, 6], 
                    [1, 2, 3], 
                    [7, 8, 4]])

print(satir_esdeger_mi(matris1, matris2))

False


# Matrislerin Tersi

In [9]:
import numpy as np

def ters_matris(matris):
    if np.linalg.det(matris) == 0: # det=0 sa ters yok
        print('Matrisin tersi yoktur.')
    else:
        Ters_matris = np.linalg.inv(matris)
        return Ters_matris 


matris = np.array([[2, 3], 
                   [1, 5]])

print(ters_matris(matris))

[[ 0.71428571 -0.42857143]
 [-0.14285714  0.28571429]]


# Matrisin Rankı

In [10]:
import numpy as np

def rank_matris(matris):
    det = np.linalg.det(matris)

    if det == 0:
        print("Matris tekil.")
    else:
        print("Matris tekil değil.")
    rank = np.linalg.matrix_rank(matris)
    return  rank

matris = np.array([[2, 1],
                   [4, 3]])

print(rank_matris(matris))

Matris tekil değil.
2


# Lineer Denklem Sistemleri

In [11]:
import numpy as np

def lineer_denklem(A, b):
    cozum = np.linalg.solve(A, b)
    return cozum

# Katsayılar matrisi A ve sabitler matrisi b'yi tanımla
A = np.array([[2, 5], 
              [4, -1]])

b = np.array([3, 2])

print(lineer_denklem(A, b))

[0.59090909 0.36363636]


# Gauss Yoketme Metodu

In [12]:
import numpy as np

def gauss_elimination(A):
    n = len(A)

    # Her sütun için
    for i in range(n):
        # Sıfır olmayan ilk elemanı 1 yapmak için satırı bölelim
        pivot = A[i][i]
        for j in range(i, n+1):
            A[i][j] /= pivot

        # Altındaki elemanları sıfırlamak için satır işlemleri yapalım
        for k in range(i+1, n):
            factor = A[k][i]
            for j in range(i, n+1):
                A[k][j] -= factor * A[i][j]

    # Geriye doğru çözüm yapalım
    x = [0] * n # Çözüm kümesini tutacak bir liste oluşturalım
    for i in range(n-1, -1, -1): # Son satırdan başlayarak yukarı doğru ilerleyelim
        x[i] = A[i][n] # Sağ taraftaki değeri alalım
        for j in range(i+1, n): # Üstündeki elemanları çıkartalım
            x[i] -= A[i][j] * x[j]

    # Çözüm kümesini döndürelim
    return x

A = [[2, 1, -2, 10],
     [3, 2, 2, 1],
     [5, 4, 3, 4]]

x = gauss_elimination(A)

print(x)

[1.0, 2.0, -3.0]


# Homojen Lineer Denklem 

In [13]:
import numpy as np

# Homojen lineer denklem sistemi AX = 0 şeklinde verilsin
# A matrisi katsayıları içersin
A = np.array([[1, 2, -3],
              [2, 5, 2],
              [3, -1, 7]])

# A matrisinin determinantını hesaplayalım
det = np.linalg.det(A)

# Determinant sıfırsa, sistem tekillik olabilir
if det == 0:
    # A matrisinin özdeğerlerini ve özvektörlerini bulalım
    eigenvalues, eigenvectors = np.linalg.eig(A)
    # Sıfır olmayan bir özdeğer varsa, sistem sonsuz çözüme sahiptir
    if any(eigenvalues != 0):
        print("Sonsuz Çözüm.")
    # Tüm özdeğerler sıfırsa, sistem sadece aşikar çözüme sahiptir
    else:
        print("Tekil Çözüm.")
# Determinant sıfır değilse, sistem tekil değildir ve sadece aşikar çözüme sahiptir
else:
    print("Sıfır Çözüm.")

Sıfır Çözüm.


# Özdeğer ve Özvektör 

In [1]:
import numpy as np

A = np.array([[2, -4], 
              [-1, -1]])

# Özdeğerleri ve özvektörleri bulma
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Özdeğerler:")
for eigenvalue in eigenvalues:
    print(eigenvalue)

print("\nÖzvektörler:")
for i in range(len(eigenvectors)):              # eigenvectors[0, i]
    normalized_eigenvector = eigenvectors[:, i] / eigenvectors[1, i]
    print(normalized_eigenvector.astype(int))

Özdeğerler:
3.0
-2.0

Özvektörler:
[-4  1]
[1 1]


# Vektör Büyüklüğü/Şiddeti

In [2]:
import math

def vektor_buyukluk(vektor):
    kare_toplam = sum([x**2 for x in vektor])
    buyukluk = math.sqrt(kare_toplam)

    if buyukluk == 1:
        print('Vektör birim vektördür.')
    else:
        print('Birim vektör değildir')

    print('Vekötürun şiddeti: \n', '√', kare_toplam, '=', buyukluk)

# Örnek kullanım
vektor = [4,3,0]
vektor_buyukluk(vektor)

Birim vektör değildir
Vekötürun şiddeti: 
 √ 25 = 5.0


## NumPy ile Vektör Büyüklüğü/Şiddeti

In [3]:
import numpy as np
x = np.array([1, 2, 0])
np.linalg.norm(x)

2.23606797749979

# İki Vektörün Skaler Çarpılması

In [4]:
def vektor_carp(vektor1, vektor2):
    if len(vektor1) != len(vektor2):
        return None
    
    skaler_carpim = 0
    for i in range(len(vektor1)):
        skaler_carpim += vektor1[i] * vektor2[i]
        
    return skaler_carpim

# Örnek kullanım
vektor1 = [1, 2, 3]
vektor2 = [4, 5, 6]
skaler_carpim = vektor_carp(vektor1, vektor2)

print("Skaler Çarpım:", skaler_carpim)

Skaler Çarpım: 32


## NumPy ile İki Vektörün Skaler Çarpılması

In [5]:
import numpy as np
vektor1 = np.array([1, 2, 3])
vektor2 = np.array([4, 5, 6])
skaler_carpim = np.dot(vektor1, vektor2)
print("Skaler Çarpım:", skaler_carpim)

Skaler Çarpım: 32


# İki Vektör Arasındaki Açı

In [6]:
import math

def vektor_acisi(vektor1, vektor2):
    if len(vektor1) != len(vektor2):
        return None
    
    dot_product = sum([vektor1[i] * vektor2[i] for i in range(len(vektor1))])
    magnitude1 = math.sqrt(sum([x**2 for x in vektor1]))
    magnitude2 = math.sqrt(sum([x**2 for x in vektor2]))
    
    cos_theta = dot_product / (magnitude1 * magnitude2)
    radian_aci = math.acos(cos_theta)
    derece_aci = math.degrees(radian_aci)
    
    return radian_aci, derece_aci

# Örnek kullanım
vektor1 = [2, 1, 1]
vektor2 = [3, -1, 2]
radian_aci, derece_aci = vektor_acisi(vektor1, vektor2)

print("Radyan Açı:", radian_aci)
print("Derece Açı:", derece_aci)

Radyan Açı: 0.7016741237876035
Derece Açı: 40.202965886569764


# Vektörel Çarpım

In [8]:
def vektorel_carpim(vektor1, vektor2):
    if len(vektor1) != 3 or len(vektor2) != 3:
        return None
    
    vektorel_carpim = [
        vektor1[1] * vektor2[2] - vektor1[2] * vektor2[1],
        vektor1[2] * vektor2[0] - vektor1[0] * vektor2[2],
        vektor1[0] * vektor2[1] - vektor1[1] * vektor2[0]
    ]
    
    return vektorel_carpim

# Örnek kullanım
vektor1 = [1, 2, 3]
vektor2 = [4, 5, 6]
vektorel_carpim = vektorel_carpim(vektor1, vektor2)

print("Vektörel Çarpım vektörü:", vektorel_carpim)

Vektörel Çarpım vektörü: [-3, 6, -3]
